# Generated by Django 2.0.2 on 2020-06-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200606_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='nub',
            field=models.IntegerField(null=True),
        ),
    ]
