# Generated by Django 2.0.2 on 2020-06-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_number_nub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='Category',
        ),
        migrations.AddField(
            model_name='number',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
